2018-10-30 15:22:42,214 ERROR: Exception on /user/imagerpg [GET] [in /Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/app/routes.py", line 71, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/app/templates/user.html", line 16, in template
    {% esle %}
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'esle'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-10-30 15:42:28,292 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-10-30 17:58:13,776 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-10-30 18:03:12,640 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-10-31 09:28:23,690 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-10-31 09:40:48,374 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-10-31 09:55:45,305 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-11-01 20:38:26,750 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-11-10 13:51:43,781 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-11-10 13:52:08,910 ERROR: Exception on /index [GET] [in /Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/app/routes.py", line 27, in index
    if posts.has_next else None
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/genepieterson/projects/flask-mega/flask-mega/ENV/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'indext' with values ['page']. Did you mean 'index' instead?
2018-11-10 14:08:06,606 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:44]
2018-11-10 14:15:48,572 INFO: Microblog startup [in /Users/genepieterson/projects/flask-mega/flask-mega/app/__init__.py:46]
